export interface IJwtPayload {
    sub: string;
    email: string;
    iat: number; // The iat (issued at) claim identifies the time at which the JWT was issued, autogenerated on sign
    exp: number; // Expiration time, autogenerated on sign
}
