version: '3'

services:
    postgres:
        image: 'postgres:11.5'
        environment:
            - 'POSTGRES_USER=gettingstarted'
            - 'POSTGRES_DB=gettingstarted'
            - 'POSTGRES_PASSWORD=postgres'
        expose:
            - '5432'
        ports:
            - '5432:5432'
    api:
        container_name: api
        build:
            dockerfile: Dockerfile
            context: .
        env_file:
            - .env
        ports:
            - 3000:3000
        depends_on:
            - postgres
        restart: always
